apiVersion: v1
kind: Pod
metadata:
  labels:
    name: oz-node
  name: oz-node
spec:
  containers:
    - image: "openshift/oz-node"
      name: oz-node
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
  volumes:
    - name: config
      secret:
        secretName: oz-config
