apiVersion: v1
kind: Pod
metadata:
  labels:
    name: oz-node
  name: oz-node
spec:
  containers:
    # Need to generate the image name from a template to be able to
    # optionally use local registry in case of deploying to something
    # other than an all-in-one cluster
    - image: "openshift/oz-node"
      name: oz-node
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
  volumes:
    - name: config
      secret:
        secretName: oz-config
